version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "${PORT}:5432"
volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data